### ISSUE TITLE
Datadog documentation

### ISSUE THREAD

**Issue by romulof** [DataDog/build-plugin#57]
### Is your feature request related to a problem? Please describe:

1. Your current documentation only mention how to send data to datadog by creating an application key, which I did, but now I get empty 403 messages probably because I haven't set the scope.
2. I don't know how to view this data in Datadog (if it had arrived there)

### Describe the solution you'd like:

1. Clear documentation on which scope is required for Datadog key that I'll use with this application
2. A small guide on how to view this data on Datadog website

### Describe alternatives you've considered:

For problem 1:
- Trial an error: not gonna happen with my company account.

For problem 2:
- Aimlessly look around Datadog trying to find the data there.

**Comment by yoannmoinet** [comment]
So sorry for the delay.

I'm not sure I fully understand your issue here.
We need an API key and not an application key.

I'll close for now as I don't think you need any scope for API keys.
Feel free to re-open with more details once you've used an API key.

FYI, we're about to release a totally new version of this plugin.
